export enum CstPisCofins {
  cst01 = 1,
  cst02 = 2,
  cst03 = 3,
  cst04 = 4,
  cst05 = 5,
  cst06 = 6,
  cst07 = 7,
  cst08 = 8,
  cst09 = 9,
  cst49 = 10,
  cst50 = 11,
  cst51 = 12,
  cst52 = 13,
  cst53 = 14,
  cst54 = 15,
  cst55 = 16,
  cst56 = 17,
  cst60 = 18,
  cst61 = 19,
  cst62 = 20,
  cst63 = 21,
  cst64 = 22,
  cst65 = 23,
  cst66 = 24,
  cst67 = 25,
  cst70 = 26,
  cst71 = 27,
  cst72 = 28,
  cst73 = 29,
  cst74 = 30,
  cst75 = 31,
  cst98 = 32,
  cst99 = 33,
}

export const CstPisCofinsLabel = new Map<number, string>([
  [CstPisCofins.cst01, '01 - Operação Tributável com Alíquota Básica'],
  [CstPisCofins.cst02, '02 - Operação Tributável com Alíquota Diferenciada'],
  [
    CstPisCofins.cst03,
    '03 - Operação Tributável com Alíquota por Unidade de Medida de Produto',
  ],
  [
    CstPisCofins.cst04,
    '04 - Operação Tributável Monofásica - Revenda a Alíquota Zero',
  ],
  [CstPisCofins.cst05, '05 - Operação Tributável por Substituição Tributária'],
  [CstPisCofins.cst06, '06 - Operação Tributável a Alíquota Zero'],
  [CstPisCofins.cst07, '07 - Operação Isenta da Contribuição'],
  [CstPisCofins.cst08, '08 - Operação sem Incidência da Contribuição'],
  [CstPisCofins.cst09, '09 - Operação com Suspensão da Contribuição'],
  [CstPisCofins.cst49, '49 - Outras Operações de Saída'],
  [
    CstPisCofins.cst50,
    '50 - Operação com Direito a Crédito - Vinculada Exclusivamente a Receita Tributada no Mercado Interno',
  ],
  [
    CstPisCofins.cst51,
    '51 - Operação com Direito a Crédito – Vinculada Exclusivamente a Receita Não Tributada no Mercado Interno',
  ],
  [
    CstPisCofins.cst52,
    '52 - Operação com Direito a Crédito - Vinculada Exclusivamente a Receita de Exportação',
  ],
  [
    CstPisCofins.cst53,
    '53 - Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno',
  ],
  [
    CstPisCofins.cst54,
    '54 - Operação com Direito a Crédito - Vinculada a Receitas Tributadas no Mercado Interno e de Exportação',
  ],
  [
    CstPisCofins.cst55,
    '55 - Operação com Direito a Crédito - Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação',
  ],
  [
    CstPisCofins.cst56,
    '56 - Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação',
  ],
  [
    CstPisCofins.cst60,
    '60 - Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita Tributada no Mercado Interno',
  ],
  [
    CstPisCofins.cst61,
    '61 - Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno',
  ],
  [
    CstPisCofins.cst62,
    '62 - Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita de Exportação',
  ],
  [
    CstPisCofins.cst63,
    '63 - Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno',
  ],
  [
    CstPisCofins.cst64,
    '64 - Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas no Mercado Interno e de Exportação',
  ],
  [
    CstPisCofins.cst65,
    '65 - Crédito Presumido - Operação de Aquisição Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação',
  ],
  [
    CstPisCofins.cst66,
    '66 - Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação',
  ],
  [CstPisCofins.cst67, '67 - Crédito Presumido - Outras Operações'],
  [CstPisCofins.cst70, '70 - Operação de Aquisição sem Direito a Crédito'],
  [CstPisCofins.cst71, '71 - Operação de Aquisição com Isenção'],
  [CstPisCofins.cst72, '72 - Operação de Aquisição com Suspensão'],
  [CstPisCofins.cst73, '73 - Operação de Aquisição a Alíquota Zero'],
  [
    CstPisCofins.cst74,
    '74 - Operação de Aquisição sem Incidência da Contribuição',
  ],
  [
    CstPisCofins.cst75,
    '75 - Operação de Aquisição por Substituição Tributária',
  ],
  [CstPisCofins.cst98, '98 - Outras Operações de Entrada'],
  [CstPisCofins.cst99, '99 - Outras Operações'],
]);
